### ISSUE TITLE
Detect nested .eslintrc file

### ISSUE THREAD

**Issue by shadyhill** [apexskier/nova-eslint-forked#19]
Thank you for working on this extension. I had more success using this over the original version. However I do seem to be running into an issue where my .eslintrc file is not getting detected when parsing the .js files. I think this has to do with my nested folder structure and was wondering if you have a suggestion for how to fix it. 

My project has a front and backend folder that looks something like this:

/project
----/frontend
--------/src
--------.eslintrc
----/backend

The JS files I want to lint all exist in the /src directory, which is why the .eslintrc file is there. If I move the .eslintrc to the project root, it is detected by the extension, but then the extension can't find any of the linting dependencies. Is there a way to specify where the linting rules should be read from?

Thank you!

**Comment by apexskier** [comment]
I think this will be fixed by https://github.com/apexskier/nova-eslint/pull/22/files#diff-364310e0b1edc562cd6e718ea63e6e04R41.

**Comment by apexskier** [comment]
@shadyhill Can you re-test this with version 1.2.0 of the extension?

**Comment by shadyhill** [comment]
@apexskier Of course! Thanks for the patch. Checking now...

**Comment by shadyhill** [comment]
@apexskier Just tested on two projects and it appears to be working as expected now. The extension is picking up the correct .eslintrc even when nested in directories within root.

Thanks again for your work on this!
