### ISSUE TITLE
.eslintrc Permission denied

### ISSUE THREAD

**Issue by devmarco** [apexskier/nova-eslint-forked#28]
After activating the extension, I'm getting the following error

`env: /Users/XX/Workspace/XXX/XXX/.eslintrc: Permission denied`

**To reproduce**

Not sure how to reproduce, It's a normal React project, with the `.eslintrc` file in the root folder.

**Expected behavior**

Eslint working properly using my existent `.eslintrc` definitions.

**Screenshots**

![Screen_Shot_2020-09-28_at_13_14_23](https://user-images.githubusercontent.com/2750520/94458882-f60c9100-018c-11eb-9eb3-a69c42321f04.jpg)

**Environment**

- Nova version: Build 204146 
- Extension version: 1.2.0 
- ESLint version: 6.4.1
- macOS version: 10.15.6  
- NodeJS information:
  - node version: 10.13.0
  - npm version: 6.4.1
  - installation method: nvm 

**Extension console output**

![Screen_Shot_2020-09-28_at_13_14_23](https://user-images.githubusercontent.com/2750520/94459131-4b48a280-018d-11eb-859a-9eaf829f207c.jpg)

**Comment by apexskier** [comment]
@devmarco Can you provide the output of `ls -l /Users/marco/Workspace/.../.eslintrc` to show me what the permissions on that file are?

**Comment by apexskier** [comment]
And what happens when you run `$(npm bin)/eslint /Volumes/Macintosh\ HD/Users/marco/Workspace/.../src/ui/components/guided-filter/guided-filter.js`?

**Comment by devmarco** [comment]
@apexskier 
>Can you provide the output of ls -l /Users/marco/Workspace/.../.eslintrc to show me what the permissions on that file are?

`-rw-r--r--  1 marco  staff  903 Sep 24 18:14 /Users/marco/Workspace/XX/XX/.eslintrc`





>And what happens when you run $(npm bin)/eslint /Volumes/Macintosh\ HD/Users/marco/Workspace/.../src/ui/components/guided-filter/guided-filter.js?

```
node_modules/eslint/bin/eslint.js src/ui/components/guided-filter/guided-filter.js

Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
/Users/marco/Workspace/XX/XX/src/ui/components/guided-filter/guided-filter.js
  66:40  warning  React Hook "useState" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return?  react-hooks/rules-of-hooks
  67:45  warning  React Hook "useState" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return?  react-hooks/rules-of-hooks

✖ 2 problems (0 errors, 2 warnings)
```

**Comment by devmarco** [comment]
@apexskier I have other Editors like `VSCode`, `Sublime`, and none of them I had to change the permissions of these files. It just works.

**Comment by devmarco** [comment]
Not sure if it's related. But the Prettier extension for example, I see this

| Prettier | Eslint |
| -- | -- |
| ![Screen_Shot_2020-09-28_at_14_41_30](https://user-images.githubusercontent.com/2750520/94467110-dbd8b000-0198-11eb-8e65-fd358a4d335c.jpg) | ![Screen Shot 2020-09-28 at 14 41 33](https://user-images.githubusercontent.com/2750520/94467208-f7dc5180-0198-11eb-8ba4-1f3ddc37a43a.png) |

**Comment by apexskier** [comment]
That's actually going to be changing in the next version, but I don't think it's related. This extension doesn't currently read files directly. The alert icon indicates it's `console.warn`, which is coming from stderr of an eslint process directly, I'm pretty sure.

**Comment by apexskier** [comment]
@devmarco I just published a small patch. I don't really think it'll fix this, but might change the output you're getting in the extension console. Can you try again and report back?

**Comment by devmarco** [comment]
@apexskier not seeing the issue more..Looks like it got fixed. Thanks
