### ISSUE TITLE
Doesn't work with @typescript-eslint

### ISSUE THREAD

**Issue by moeriki** [apexskier/nova-eslint-forked#55]
ESLint runner outputs this error per file I have open.

![image](https://user-images.githubusercontent.com/38758/97166659-e7ae9680-1785-11eb-9eb0-6e302fceab8c.png)

> // Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser. The file does not match your project config: ../../../../../Volumes/Macintosh HD/Users/moeriki/Projects/XploreWoods/product-master-services/functions/v1-feed-consumer/src/v1-model-service.ts. The file must be included in at least one of the projects provided.

The mixed absolute / relative filepath makes me think a filepath somewhere is handled or translated wrongly.

The ESlint CLI works fine. The VSCode ESLint plugin has no issues with this project.

![image](https://user-images.githubusercontent.com/38758/97166980-6277b180-1786-11eb-8445-35e4c4a0c916.png)

**To reproduce**

I don't have a minimal reproduction demo but I can make one if requested. ~I currently assume a simple setup with ESlint / TS would give an issue.~

**Expected behavior**

ESLint runs fine.

**Environment**

- Nova version: 2 (build 213794)
- Extension version: 1.2.1
- ESLint version: 7.11.0
- @TS-ESLint version: 3.10.0
- macOS version: 11.0 Beta (20A5395g)
- NodeJS information: 
  - node version: 10.16.3
  - yarn version: 1.22.5
  - installation method: asdf-nodejs

**Extension console output**

No errors.

**Comment by apexskier** [comment]
A minimal repro would be appreciated! This and a couple other projects I have use eslint and typescript and I haven't seen this in them.

**Comment by moeriki** [comment]
Ah interesting. Thanks for the feedback. I'll see to make a minimal reproduction.

**Comment by moeriki** [comment]
Found it easy to produce. Just fill in the parserOptions project configuration.

```json
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": { "project": "tsconfig.json" }
}
```

https://github.com/Moeriki/bug-nova-typescript-eslint

**Comment by apexskier** [comment]
I found the issue. Nova prefixes file uris with `/Volumes/Macintosh HD`, which eslint doesn't handle well. I've run into a few other issues with this Nova behavior.

If I run `cat src/index.ts | eslint --stdin --stdin-filename '/Volumes/Macintosh HD/Users/cameronlittle/Dev/bug-nova-typescript-eslint/src/index.ts'` on the cli I get the same error as in the editor.

**Comment by apexskier** [comment]
The big issue with `/Volumes/Macintosh HD` is that without a workspace I don't have a great way to check if the root volume is _actually_ called "Macintosh HD" or not - env vars don't contain a volume. I have to guess.

`nova.extension.path`, `nova.extension.globalStoragePath`, `nova.extension.workspaceStoragePath`, and env vars give me `/Users/cameronlittle/...`

**Comment by apexskier** [comment]
Also, duplicate of #56
