### ISSUE TITLE
Documentation for newbies

### ISSUE THREAD

**Issue by robinstewart** [apexskier/nova-eslint-forked#57]
Would you mind adding full instructions for setting up the plugin for those of us who haven't used ESLint before?

1. Do I need to separately install ESLint on my system?
2. Do I need to set up a custom `.eslintrc.js` file?
3. Any other setup steps?

So far I've only added a `.eslintrc.js` file to my project directory (based on documentation at https://eslint.org). I'm not seeing any ESLint issues show up in my `.js` files even when I add obviously wrong code, so it's not working yet.

**Environment**

- Nova version: 2.0
- Extension version: 1.2.1
- macOS version: 10.15.7

**Extension console output**

ESLint[17:52:14.266000] activating...
ESLint[17:52:14.267000] activated

**Comment by apexskier** [comment]
Take a look at https://github.com/apexskier/nova-eslint/pull/60 and let me know if it helps!

**Comment by robinstewart** [comment]
Yes, this is what I needed, thank you!

You might also just clarify that the "Path to ESLint executable" preference is part of the Nova extension (vs. part of the ESLint installation).

**Comment by apexskier** [comment]
Unfortunately Nova doesn't yet have documentation for extension preferences in their help library, so I can't link to official docs, but that's a good note
