### ISSUE TITLE
Support additional file types

### ISSUE THREAD

**Issue by apexskier** [apexskier/nova-eslint-forked#9]
https://discord.com/channels/756815974128418817/756817436363194401/756878326404087908

Currently, this extension is limited to only javascript, typescript, jsx, and tsx files. Eslint can operate on other types, such as vue, html, etc when used with plugins (see https://github.com/eslint/rfcs/pull/20). This plugin should have parity with [eslint's core features](https://eslint.org/docs/user-guide/configuring#specifying-target-files-to-lint).

Unfortunately, since command applicable syntax is [currently static in the extension manifest](https://github.com/apexskier/nova-eslint/blob/1681bba35e285eca81e8796bd0d39a7cf6b65f22/ESLint.novaextension/extension.json#L62), this is "all or nothing" for commands and can't easily be user configured. We can support dynamic user configuration for [inline functionality though](https://github.com/apexskier/nova-eslint/blob/1681bba35e285eca81e8796bd0d39a7cf6b65f22/src/main.ts#L58).

[VSCode's plugin appears to default to checking html and vue](https://github.com/microsoft/vscode-eslint/blob/b4124f9383121c5f293a1068288e99f77019229d/README.md#settings-options), so it's probably acceptable to do that here as well.

**Comment by apexskier** [comment]
Slightly more complicated than I was expecting - merely adding html as a filetype breaks things (probably because it doesn't use the right parser). We might need something in the eslint runner to load configuration for a specific file (possibly through #10).

**Comment by tommasongr** [comment]
I would really like to give you a hand but I'm not aware of the big picture of ESLint, if I'll find time to give it a look I'll do my best to help on this! 💪

**Comment by tommasongr** [comment]
Hi @apexskier
I tried the branch with support of additional file types in a vue project and as far as I've seen it all works correctly! Do you still have problems on that??

**Comment by apexskier** [comment]
Last I tried this broke for html files in a non-vue project.

**Comment by tommasongr** [comment]
What kind of broke? I would like to try and see

**Comment by apexskier** [comment]
I'm seeing a parsing error in my test html file. ([code is here](https://github.com/apexskier/nova-eslint/compare/master...apexskier:additional-file-types))
<img width="343" alt="Screen Shot 2020-09-24 at 20 49 51" src="https://user-images.githubusercontent.com/329222/94186879-82763580-fea7-11ea-9dde-7f20f0dc2b31.png">

**Comment by apexskier** [comment]
I found one issue (although I suspect there'll be another) - the `uri` passed to the eslint process doesn't work, since eslint isn't able to resolve `file:` uris to find the right config file.

**Comment by apexskier** [comment]
Fixed that, but the next issue is that parsing won't work unless you have the extension installed that sets up parsing for the custom file types (so you'll get warnings like this).

**Comment by apexskier** [comment]
It looks like the vscode extension _might_ be checking configured plugins to determine file type support -https://github.com/microsoft/vscode-eslint/blob/31b3f27aaf6d6f9c47c7395f0cb5e976ed0e54cd/server/src/eslintServer.ts#L648

**Comment by soniktrooth** [comment]
Is this a 'closed won't fix'? I would love some es-lint happening in script blocks of `.vue` files.

**Comment by apexskier** [comment]
Nope, support has been added, see the linked PR.
